version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
      - ./vote:/app
    ports:
      - "5000:80"
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    build: ./worker
    depends_on:
      - redis
      - db

  db:
    image: mysql/mysql-server:latest
    ports: 
      - "3306:3306"
