version: "3"

services:
  vote:
    build: ./vote
    command: python app.py
    volumes:
      - ./vote:/app
    ports:
      - "5000:80"
    depends_on:
      - redis
  
  redis:
    image: redis:alpine
    ports: ["6379"]

  worker:
    build: ./worker
    # environment:      
    #   - "ConnectionStrings:VoteData=Server=db;Port=3306;Database=votes;User=root;SslMode=None"
    depends_on:
      - redis
      - db

  db:
    image: mysql
    ports: 
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql@123
      MYSQL_DATABASE: votes
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080